// Recorte de ícones Font Awesome Solid (a mesma família já carregada em layout.js) que fazem
// sentido pra marcos de jornada/carreira. `keywords` mistura PT/EN pra pesquisa funcionar nos dois.
const ICONS = [
  ["graduation-cap", "formatura graduação educação school graduation education"],
  ["user-graduate", "estudante formando student graduate"],
  ["school", "escola colégio school"],
  ["chalkboard-user", "professor aula lousa teacher classroom"],
  ["book", "livro leitura book"],
  ["book-open", "livro aberto estudo reading book open"],
  ["book-open-reader", "leitura estudo reading"],
  ["code", "código programação code programming"],
  ["laptop-code", "programação notebook code laptop"],
  ["terminal", "terminal console"],
  ["code-branch", "git branch versionamento"],
  ["code-compare", "code review comparação"],
  ["bug", "bug erro debug"],
  ["microchip", "hardware chip iot esp32"],
  ["robot", "robô automação robot"],
  ["rocket", "lançamento startup rocket launch"],
  ["briefcase", "trabalho emprego job work"],
  ["briefcase-medical", "saúde medicina health"],
  ["building", "empresa prédio company building"],
  ["industry", "indústria fábrica industry factory"],
  ["gear", "engrenagem configuração settings gear"],
  ["gears", "engrenagens settings"],
  ["wrench", "ferramenta manutenção tool"],
  ["screwdriver-wrench", "ferramentas manutenção tools"],
  ["hammer", "martelo construção hammer"],
  ["toolbox", "caixa de ferramentas toolbox"],
  ["hard-hat", "capacete obra engenharia construction"],
  ["drafting-compass", "engenharia design compass"],
  ["ruler-combined", "medida régua design ruler"],
  ["database", "banco de dados sql database"],
  ["server", "servidor backend server"],
  ["cloud", "nuvem cloud"],
  ["mobile-screen", "celular app mobile"],
  ["desktop", "computador desktop"],
  ["display", "tela monitor display"],
  ["network-wired", "rede network"],
  ["wifi", "wifi rede internet"],
  ["plug", "conector plug hardware"],
  ["bolt", "energia rápido bolt fast"],
  ["bolt-lightning", "raio energia lightning"],
  ["lightbulb", "ideia inovação idea innovation"],
  ["flask", "laboratório ciência experiment lab"],
  ["flask-vial", "experimento ciência lab"],
  ["atom", "ciência física atom science"],
  ["dna", "biologia genética dna"],
  ["microscope", "pesquisa ciência research"],
  ["calculator", "matemática cálculo math"],
  ["chart-line", "gráfico crescimento growth chart"],
  ["chart-simple", "gráfico dados chart"],
  ["chart-pie", "gráfico pizza chart"],
  ["chart-column", "gráfico barras chart"],
  ["diagram-project", "projeto diagrama project"],
  ["sitemap", "estrutura mapa site sitemap"],
  ["layer-group", "camadas stack layers"],
  ["cube", "3d objeto cube"],
  ["cubes", "blocos cubes"],
  ["puzzle-piece", "peça integração puzzle plugin"],
  ["palette", "design cor arte palette design"],
  ["pen-nib", "design escrita pen"],
  ["pencil", "editar lápis edit pencil"],
  ["paintbrush", "arte design pincel brush"],
  ["camera", "foto câmera photo camera"],
  ["video", "vídeo video"],
  ["film", "filme cinema film"],
  ["music", "música music"],
  ["headphones", "áudio fone audio headphones"],
  ["gamepad", "jogo game"],
  ["dice", "jogo sorte dice game"],
  ["trophy", "conquista prêmio troféu award trophy"],
  ["medal", "medalha conquista medal"],
  ["award", "prêmio reconhecimento award"],
  ["star", "destaque estrela star"],
  ["certificate", "certificado diploma certificate"],
  ["id-badge", "crachá identidade badge"],
  ["id-card", "identidade carteira id card"],
  ["user", "pessoa perfil user"],
  ["user-tie", "profissional executivo professional"],
  ["users", "equipe grupo team group"],
  ["people-group", "equipe comunidade team community"],
  ["handshake", "acordo parceria partnership deal"],
  ["comments", "conversa chat comments"],
  ["comment", "comentário mensagem message"],
  ["envelope", "email carta envelope"],
  ["phone", "telefone contato phone"],
  ["globe", "mundo internet global web"],
  ["map", "mapa localização map"],
  ["location-dot", "local pin location"],
  ["house", "casa início home house"],
  ["store", "loja negócio shop store"],
  ["cart-shopping", "compras loja cart shopping"],
  ["dollar-sign", "dinheiro finanças money dollar"],
  ["coins", "dinheiro moedas coins money"],
  ["piggy-bank", "economia poupança savings"],
  ["seedling", "início crescimento growth start seedling"],
  ["leaf", "sustentável natureza leaf eco"],
  ["heart", "saúde favorito health heart"],
  ["shield", "segurança proteção security shield"],
  ["shield-halved", "segurança security"],
  ["lock", "segurança senha lock security"],
  ["key", "acesso chave key access"],
  ["fingerprint", "biometria segurança fingerprint"],
  ["eye", "visão observação eye view"],
  ["magnifying-glass", "busca pesquisa search"],
  ["flag", "marco meta flag milestone"],
  ["flag-checkered", "conclusão fim finish flag"],
  ["mountain", "desafio conquista challenge mountain"],
  ["plane", "viagem plane travel"],
  ["satellite", "iot satélite satellite"],
  ["satellite-dish", "ao vivo transmissão live"],
  ["route", "trajetória jornada caminho route journey"],
  ["road", "caminho estrada road path"],
  ["compass", "direção orientação compass"],
  ["calendar", "data calendário calendar"],
  ["calendar-check", "concluído data agendado done calendar"],
  ["clock", "tempo horário clock time"],
  ["hourglass", "tempo espera hourglass"],
  ["hourglass-half", "em andamento progresso in progress"],
  ["forward", "avanço próximo next forward"],
  ["meteor", "impacto meteor"],
  ["moon", "noite estudo noturno moon"],
  ["sun", "dia claro sun"],
  ["wand-magic-sparkles", "mágica efeito magic"],
  ["gem", "valor qualidade gem premium"],
  ["crown", "liderança rei lead crown"],
  ["chess-knight", "estratégia chess strategy"],
  ["dumbbell", "esforço treino effort gym"],
  ["person-running", "progresso corrida running progress"],
  ["arrow-trend-up", "crescimento progresso growth trend"],
  ["infinity", "contínuo infinito continuous infinity"],
];

export default ICONS;
